module.exports = [
    
      {
        mainDnt : 'appellationtable.dnt', 
        type : 'titles', 
        minLevel: 0, 
        minRank: 0
      },
      // wspr: { mainDnt: 'itemtable_source.dnt', type: 'wellspring', minLevel: 24 },
      
      { 
        mainDnt: 'itemtable_skilllevelup.dnt', 
        potentialDnt: 'potentialtable.dnt',
        sparkDnt: 'potentialtable_potentialjewel.dnt',
        type: 'techs', 
        minLevel: 60,
        minRank: 0 },
      
      { 
        mainDnt: 'itemtable_talisman.dnt', 
        type: 'talisman', 
        potentialDnt: 'potentialtable_talismanitem.dnt',
        minLevel: 24, 
        minRank: 0 },
      
      { 
        mainDnt: 'itemtable_dragonjewel.dnt', 
        potentialDnt: 'potentialtable_dragonjewel.dnt',
        enchantDnt: 'enchanttable_dragonjewel.dnt', 
        gemDnt: 'dragonjeweltable.dnt',
        type: 'gems',
        minLevel: 70, 
        minRank: 3 },
      
      { 
        mainDnt : 'itemtable_glyph.dnt', 
        potentialDnt: 'potentialtable_glyph.dnt',
        type: 'plates',
        minLevel: 40, 
        minRank: 2 },

      {
        mainDnt : 'itemtable_glyph95.dnt', 
        potentialDnt: 'potentialtable_glyph95.dnt',
        type: 'plates',
        minLevel: 1,
        minRank: 1,
      },

      {
        mainDnt: 'itemtable.dnt', 
        partsDnt: 'partstable.dnt', 
        weaponDnt: 'weapontable.dnt', 
        enchantDnt: 'enchanttable.dnt', 
        potentialDnt: 'potentialtable.dnt',
        setDnt: 'setitemtable.dnt',
        type: 'equipment',
        minLevel: 80, 
        minRank: 3 },
        
      {
        mainDnt: 'itemtable_equipment.dnt', 
        partsDnt: 'partstable_equipment.dnt', 
        weaponDnt: 'weapontable_equipment.dnt', 
        enchantDnt: 'enchanttable.dnt', 
        potentialDnt: 'potentialtable.dnt',
        sparkDnt: 'potentialtable_potentialjewel.dnt',
        setDnt: 'setitemtable.dnt',
        type: 'equipment',
        minLevel: 40, 
        minRank: 3 },
      { 
        mainDnt: 'itemtable_reboot.dnt', 
        partsDnt: 'partstable_reboot.dnt', 
        weaponDnt: 'weapontable_reboot.dnt', 
        enchantDnt: 'enchanttable_reboot.dnt', 
        potentialDnt: 'potentialtable_reboot.dnt',
        setDnt: 'setitemtable.dnt',
        type: 'equipment',
        minLevel: 40, 
        minRank: 3 },
      { 
        mainDnt: 'itemtable_pvp.dnt',
        partsDnt: 'partstable_pvp.dnt', 
        weaponDnt: 'weapontable_pvp.dnt', 
        enchantDnt: 'enchanttable.dnt', 
        setDnt: 'setitemtable.dnt',
        type: 'equipment',
        minLevel: 40, 
        minRank: 3 },
      { 
        mainDnt: 'itemtable_cashclone.dnt', 
        partsDnt: 'partstable_cashclone.dnt', 
        type: 'cash',
        minLevel: 0, 
        minRank: 4 },
      { 
        mainDnt: 'itemtable_common2017.dnt', 
        partsDnt: 'partstable_common2017.dnt', 
        weaponDnt: 'weapontable_common2017.dnt', 
        setDnt: 'setitemtable_cash.dnt',
        type: 'cash',
        minLevel: 0, 
        minRank: 0 },
      { 
        mainDnt: 'itemtable_common2016.dnt', 
        partsDnt: 'partstable_common2016.dnt', 
        weaponDnt: 'weapontable_common2016.dnt', 
        setDnt: 'setitemtable_cash.dnt',
        type: 'cash',
        minLevel: 0, 
        minRank: 0 },
      { 
        mainDnt: 'itemtable_common2015.dnt', 
        partsDnt: 'partstable_common2015.dnt', 
        weaponDnt: 'weapontable_common2015.dnt', 
        setDnt: 'setitemtable_cash.dnt',
        type: 'cash',
        minLevel: 0, 
        minRank: 0 },
      { 
        mainDnt: 'itemtable_common2014.dnt', 
        partsDnt: 'partstable_common2014.dnt', 
        weaponDnt: 'weapontable_common2014.dnt', 
        setDnt: 'setitemtable_cash.dnt',
        type: 'cash',
        minLevel: 0, 
        minRank: 0 },
      { 
        mainDnt: 'itemtable_cash.dnt', 
        partsDnt: 'partstable_cash.dnt', 
        weaponDnt: 'weapontable_cash.dnt', 
        setDnt: 'setitemtable_cash.dnt',
        type: 'cash',
        minLevel: 0, 
        minRank: 0 },
      {
        mainDnt: 'itemtable_event.dnt', 
        partsDnt: 'partstable_event.dnt',
        weaponDnt: 'weapontable_event.dnt',
        setDnt: 'setitemtable_cash.dnt',
        type: 'cash',
        minLevel: 0, 
        minRank: 0 },
      {
        mainDnt: 'itemtable_vehicle.dnt',
        partsDnt: 'vehiclepartstable.dnt',
        setDnt: 'setitemtable_cash.dnt',
        type: 'xtras',
        minLevel: 0,
        minRank: 0 },
      {
        mainDnt: 'itemtable_imprinting.dnt',
        type: 'imprint',
        minLevel: 0,
        minRank: 0 },
    ];
